import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export default function Home() {

  const router = useRouter();
  const currentUser = false;

  const onLink = (href) => {
    router.push(href)
  }

  const handleEnter = () => {
    if (currentUser) {
      onLink('/login')
    } else {
      onLink('/signup')
    }
  }

  return (
    <div>
      <Head>
        <title>Game Creations
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems :'center',
          backgroundColor: 'pink',
          height: '100vh',
          width: '100%'
        }}>
        <Typography
          variant='h3'
          sx={{
            textAlign: 'center',
            width: '300px'
          }}>
          {'Welcome to the Arcade'}
        </Typography>

        <Button
          variant='contained'
          sx={{
            width: '20vh',
            margin: '20px'
          }}
          onClick={handleEnter}
          >Enter
        </Button>

      </Box>
    </div>
  )
}

