import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Game Creations
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems :'center',
          backgroundColor: 'pink',
          height: '100vh',
          width: '100%'
        }}>
        <h1>Let's Play!</h1>

        <Button
          variant='contained'
          sx={{
            width: '20vh',
            margin: '20px'
          }}
          >Login
        </Button>

        <Button
          variant='contained'
          sx={{
            width: '20vh',
            margin: '20px'
          }}
          >Sign-In
        </Button>

      </Box>
    </div>
  )
}
